config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :sellers,:loactions
  resources :pages ,excecpt: [:show]
  resources :cars do
    collection do
      get "search"
    end
  end
  get 'home/index'
  get 'home/About'
  get 'cars/index'
  get 'sellers/index'
  get 'cars/:id', to: 'cars#show'
  get 'sellers/:id', to: 'sellers#show'
  get "loactions/:id", to: "loactions#show"
  root "home#index"
  get '/pages/:permlink' => "pages#permlink", as: 'permlink'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_location.rb
class CarLocation < ApplicationRecord
  has_many :car_sales

  validates :state, :region, presence: true
  validates :region, uniqueness: true
  #validates :lat,:long, numericality: true
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  has_many :car_sales

  validates :year, :manufacturer, :modelnumber, presence: true
  #validates :modelnumber, uniqueness: true
  validates :year, numericality: true
end

app/models/car_sale.rb
class CarSale < ApplicationRecord
  belongs_to :car_seller
  belongs_to :car_model
  belongs_to :car_location

  validates :price, :VIN, :odometer, presence: true
  validates :VIN, uniqueness: true
end

app/models/car_seller.rb
class CarSeller < ApplicationRecord
  has_many :car_sales

  validates :name, :phoneNumber, :email, presence: true
  validates :email, uniqueness: true

end

app/models/loaction.rb
class Loaction < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :cms_pages
  def cms_pages
      Page.all
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    #@cars = CarSale.includes(:car_location).order("price DESC").limit(20)
    @cars = Kaminari.paginate_array(CarSale.first(300)).page(params[:page])

  end

  def show
  @car = CarSale.find(params[:id])
  #@car = CarSale.find(21031)
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    search_type = "%#{params[:search_type]}%"
    @CarSaleFinds = Kaminari.paginate_array(CarSale.where("#{params[:search_type]} LIKE ? ",wildcard_search)).page(params[:page])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cars = CarSale.includes(:car_model).order("price DESC").limit(10)

  end

  def About
    @pages = Page.all
  end


end

app/controllers/loactions_controller.rb
class LoactionsController < ApplicationController

  # GET /loactions or /loactions.json
  def index

    #@loactions = CarLocation.includes(:car_sales).order("id DESC").limit(10)
    @loactions = Kaminari.paginate_array(CarLocation.first(300)).page(params[:page])
  end

  # GET /loactions/1 or /loactions/1.json
  def show
    @loaction = CarLocation.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /pages or /pages.json
  def aboutus
    @pages = Page.all
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def index
    @sellers = CarSeller.includes(:car_sales).order("name DESC").limit(200)
  end

  def show
  @seller = CarSeller.find(params[:id])
  @carlistings = CarSale.where("car_seller_id = ? ",params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loactions_helper.rb
module LoactionsHelper
end

app/views/cars/index.html.erb
<%= render partial: 'common/header'%>
<h1>New cars Sales</h1>
<div class = "columns">
  <div class = "column">
    <%= form_with(url: search_cars_path , method: :get, local: true) do %>
      <div class= "field is-grouped mb-5">
        <div class= "control is-expanded">
          <%= text_field_tag(:keywords, nil ,class: "input", placeholder: "Find the right Car")%>
          <div class="form_row">
          <label> Search by:</label>
            <%= radio_button_tag(:search_type,"Description", true)%>
            <label >Description</label>
            <%= radio_button_tag(:search_type, "VIN", false)%>
            <label>VIN</label>
            <%= radio_button_tag(:search_type,"Price",false )%>
            <label >Price</label>
          </div>
        </div>
      </div>
      <div class="control">
        <%= submit_tag("Search" , class: "button is-priamry")%>
      </div>
    <%end%>
  </div>
</div>



<ol class="ml-5">
<% @cars.each do |car|%>
<li>
<%= car.price %>
<em><%= car.odometer %></em>
<em><%= link_to "show", car_path(car) %></em>
</li>
<%end%>
</ol>
<%= paginate @cars %>
<%= page_entries_info @cars %>

<%= render partial: 'common/footer'%>

app/views/cars/search.html.erb
<%= render partial: 'common/header'%>
<p class = "mb-5">
  Found <%= pluralize(@CarSaleFinds.count, "Car")%> when searching for: <%= params[:keywords]%>
</p>
<ul>
<% params.each do |key,value|%>
 <% Rails.logger.warn "Param #{key}: #{value}" %>
<%end%>
</ul>
<% @CarSaleFinds.each do |carsale|%>
<ul>
<li>Car Model Year <%= carsale.car_model.year%></li>
<li>Car Manufacturer <%= carsale.car_model.manufacturer%></li>
<li>Price <%= carsale.price%></li>
<li><%= link_to "show", car_path(carsale) %></li>
</ul>
<%end%>

<%= paginate @CarSaleFinds %>
<%= page_entries_info @CarSaleFinds %>


<%= render partial: 'common/footer'%>

app/views/cars/show.html.erb
<%= render partial: 'common/header'%>
<h2 class= "title is 2">

<%= @car.car_model.year%>
<%= @car.car_model.modelnumber%>
</h2>
<div class="message-header">
<p>Description</p>
</div>
<div class="message-body">
<%= @car.description%>
</div>

<p class = 'md-5'>
<strong>Manufacturer </strong>
<%= @car.car_model.manufacturer %>
</p>
<p class = 'md-5'>
<strong>Cylinders </strong>
<%= @car.car_model.cylinders %>
</p>
<p class = 'md-5'>
<strong>Transmission </strong>
<%= @car.car_model.drive %>
</p>

<p class = 'md-5'>
<strong>Price  </strong>
<%= @car.price%>
</p>
<p>
<strong>Condition</strong>
<%= @car.condition%>
</p>
<p>
<strong>VIN </strong>
<%= @car.VIN%>
</p>
<h3>Contact info</h3>
<p> <a href="/sellers/<%= @car.car_seller_id %>">see other listings form this user</a> </p>
<p>
<%= @car.car_seller.name%>
</p>
<p>
<%= @car.car_seller.phoneNumber%>
</p>
<p>
<%= @car.car_seller.email%>
</p>

<%= render partial: 'common/footer'%>

app/views/common/_footer.html.erb
<hr>
<footer>
<p><em>this is a footer</em></p>
<ul class="mt-5">

<% cms_pages.each do |page| %>
  <li><%= link_to page.title, '/home/About' %></li>
<% end %>

</ul>
</footer>

app/views/common/_header.html.erb

<header>
<h2 class = "column" > Jake Website</h2>
<ol class="mt-5">
  <li><%= link_to "Home", root_path%>  <%= link_to "Cars", cars_path() %> Car Models <%= link_to "Sellers", sellers_path() %> <%= link_to "Car locations", loactions_path() %>   <% cms_pages.each do |page| %>
  <%= link_to page.title, '/home/About' %>
  <% end %></li>
</ol>
</header>

app/views/home/About.html.erb
<%= render partial: 'common/header'%>
<h1></h1>

<div class = "columns">
<div class = "column">


<ol class="ml-5">
<% @pages.each do |page|%>
<li>
<%= page.title %>
<em><%= page.content %></em>
</li>
<%end%>
</ol>

</div>
</div>
<%= render partial: 'common/footer'%>

app/views/home/index.html.erb
<%= render partial: 'common/header'%>
<h1>New cars Sales</h1>

<div class = "columns">
<div class = "column">


<ol class="ml-5">
<% @cars.each do |car|%>
<li>
<%= car.price %>
<em><%= car.odometer %></em>
<em><%= link_to "See all cars", cars_path %></em>
</li>
<%end%>
</ol>

</div>
</div>
<%= render partial: 'common/footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntroProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loactions/_form.html.erb
<%= form_with(model: loaction) do |form| %>
  <% if loaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(loaction.errors.count, "error") %> prohibited this loaction from being saved:</h2>

      <ul>
        <% loaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/loactions/_loaction.html.erb
<div id="<%= dom_id loaction %>">
</div>

app/views/loactions/edit.html.erb
<h1>Editing loaction</h1>

<%= render "form", loaction: @loaction %>

<br>

<div>
  <%= link_to "Show this loaction", @loaction %> |
  <%= link_to "Back to loactions", loactions_path %>
</div>

app/views/loactions/index.html.erb
<p style="color: green"><%= notice %></p>



<%= render partial: 'common/header'%>
<h1>Loaction</h1>

<div class = "columns">
<div class = "column">


<ol class="ml-5">
<% @loactions.each do |loaction|%>
<li>
<%= loaction.state %>
<em><%= loaction.region %></em>
<em> <a href="/loactions/<%= loaction.id %>">show on map</a></em>
</li>
<%end%>

</ol>
<%= paginate @loactions %>
<%= page_entries_info @loactions %>




</div>
</div>
<%= render partial: 'common/footer'%>

app/views/loactions/new.html.erb
<h1>New loaction</h1>

<%= render "form", loaction: @loaction %>

<br>

<div>
  <%= link_to "Back to loactions", loactions_path %>
</div>

app/views/loactions/show.html.erb
<%= render partial: 'common/header'%>
<h1>Loaction</h1>

<div class = "columns">
<div class = "column">



<p>
<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=7&size=1000x1000&center=#{@loaction.lat},#{@loaction.long}&markers=size:small%7Ccolor:red%7C#{@loaction.lat},#{@loaction.long}&key=#{'AIzaSyCRYFKAAL1L7FHCEm3gz4d-F3dI_ywkMMY'}", alt: "Map" %>
</p>

</div>
</div>
<%= render partial: 'common/footer'%>

app/views/sellers/index.html.erb
<%= render partial: 'common/header'%>



<ol class="ml-5">
<% @sellers.each do |seller|%>
<li>
<%= seller.name %>
<em><%= seller.phoneNumber %></em>
<em> <a href="/sellers/<%= seller.id %>">see all listings</a></em>

</li>
<%end%>
</ol>



<%= render partial: 'common/footer'%>

app/views/sellers/show.html.erb
<%= render partial: 'common/header'%>


<ol class="ml-5">
<% @carlistings.each do |seller|%>
<li>
<%= seller.price %>
<em><%= seller.VIN %></em>
<em> <a href="/cars/<%= seller.id %>">see this listing</a></em>

</li>
<%end%>
</ol>




<%= render partial: 'common/footer'%>